import './Footer.css'

export default function Footer() {
	return (
		<footer className='relative md:absolute'>
			<span>
				2022
				<a href='https://albertovelez.dev' target='_blank' className='ml-2 hover:text-indigo-700'>
					Alberto Vélez
				</a>
			</span>
			<a href='https://www.linkedin.com/in/alberto-v%C3%A9lez-51155320/' target='_blank'>
				<img
					class='nav__icon'
					src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAh1BMVEUAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQGZGjCnAAAALHRSTlMAWTL5mSFgSOPcfQuzLhPvg24Z2M6HaxAGKumujnjyyL++lZFkVk49vKmeQAgO/74AAAEfSURBVDjLlZLZbsMgEEWvTSg23hovjZ2t2dOF//++ekKCDcVVcx7QII7Q3NHgOXKeZR1P4Ke8rPfRlhVVKq8eZ3F6Vwa2Eq37eaosWAOLLFIuu2T8Xqjf1IORR8pHmj/6S/X9kzmGhOakiDkQOEIR6vw63zfAlcMRxEVfPvLFyhUiTsJaTXOmCHtdr4Vo1EGIeSV4t7n3S+Pi94wv1OQbUC4A0++MhrQdCXNKHZT9GQ8Cs4W2VjGALyN0hS1kfd0Br0bglS2EfR2OhSS1mzSCGbb8QxAkXNmkUJckJKtJYYMb4vbFMo6XdNDcojimbBXXQtsoLyzAg51XkK0RktrzfsAADcOBSVjk0l7sKmjhEB6jYeM3HB74uZkRUpT4Pz9F8lfgIdltSgAAAABJRU5ErkJggg=='
					alt='LinkedIn icon'
				/>
			</a>
			<a id='email-link' href='mailto:albertovelezdev@gmail.com'>
				<img
					id='email-icon'
					class='nav__icon'
					src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAh1BMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD3YishAAAALHRSTlMA+2Ze4fgGA+XMWhsQC/Dq0mEsFPSyjU1BGNrBuaSGd1dRPDYoH9yomJFySS36zIAAAAD0SURBVDjLvZBrz4IwDIU73BgMuYmCeL++1/7/32driJMo/aLxSZalOyen7eANTNxoEHcGcFoNYxYH0CgSA8oo+JINCzitJH01AahqNZhfV0CEZf5cz8uQ5JTO/Okqek7SGJZnupLZY5tZwr9Ia0b/ltpsp305+6N463IDiGbDbY7FvV4cOf5HoQIulycuf28h03p8jUdkA5OPQp61C4kP3DTI0BtQrVsO2UY0fJD6sdnQoRtL763b89/YPS/eN6BZJ9CRfBv0Bk9UpiynATXqGXwVN1W7KxQOGLjWkZe9QYANMp8wZLKuYWMkPSvB7gKBBl7nAo5Lb9fY2QUlAAAAAElFTkSuQmCC'
					alt='Email icon'
				/>
			</a>
			<a href='https://github.com/avelezdo/resize-images' target='_blank'>
				<img
					src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAllBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6C80qAAAAMXRSTlMA+OIxCfzx+uwW9VkPBgTYw9KFaCgk6ZR0YVJDIBrczcm0q48+LOa9ua+ffG5MR9SGVL+KuAAAAWdJREFUOMt9Uud6gzAMFB5swgwJ2aMZzWr9/i9XW3YgYL7eD8C6s3SSgA7x85jVnJ+z4sXAxnTmiBbu73pAs8ITPTjzpHf9R1jIgo6nvhgBWbX3NW8rTA6WykN+cT85/0pUFe1jpiJLYHdfuOl2uwnF+ZFAqaJzxVfoX9ULKmMpVg/sRXV7wJxrGKDCcAEQ6/l8DQWRnhiDUhuOh4LAF9rbN74XYGFuauRoJrYFAZq/AmbKYQQEawPqsjFBqhgP+P8ZOOCEw4nNM+zfhw2apbbghcQO9vieWbwhjqbd0J6kYwa00h+kP6pJU2PYCQAuMs+dCPcQTY3V5NTsQ4G4yeOSix2lRKo3BSBu5P0Heyd5VNtIg0XYrTRCsvM+laMoodmmB2a28ObrdWu4XkHCWoeGD5dg8HAEKU8V7QvCCFo0rvTo8ncXyPtP+ADdqZgRMLWkrIIe4jLlPDEC7uURgyFiStt8tKP/AN6xSzqdzJ8HAAAAAElFTkSuQmCC'
					width='32'
					class='project__link'
					alt='Portfolio Github Repo'
				/>
			</a>
			<a href='https://twitter.com/avelezdo' target='_blank'>
				<img
					id='twitter-icon'
					class='nav__icon'
					src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAhFBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8qm6wAAAAK3RSTlMA+gXpUfPIXQvc76dmRjMaE+vOr6ujlHcK1L+1joVsYlhWKyXBuppwTDsXZs3vIQAAAPBJREFUOMvFkVeywjAMReWS2OmFQEJv79G0//0RexKQwfzC+bJ1z3iuR/ATeBtW8XxVmnPO+7ty80OElvii1eLUD1Lc0bwQOMAYils/SZBtiDDBJ9E13QIsEXHaPR5gRIgx1OYF48pBUEgJS9NhOO+5EVon12bUja1Esz3ylAoTsOzIiAVUmNp8LVuGftZWaPAjivT2kluBR5/ygIMloxXcjgOy8gvZKOhiFnjyiI9Cjl4k3aCHP3iia88XjkDg7yUkuHRy7uRneCFf0Jht3LTY/yNFZCSUyzpGl6QESrkSTvvmAG9ks1CYhVR1ojR8nTseXU/MGEPN/gAAAABJRU5ErkJggg=='
					alt='Twitter icon'
				/>
			</a>
		</footer>
	)
}
